name: vayufy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.0.0
  curved_navigation_bar: ^1.0.3
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  google_sign_in: ^7.2.0
  http: ^1.2.1
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.0.0

  cupertino_icons: ^1.0.8
  syncfusion_flutter_charts: ^26.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  google_fonts: ^6.2.1

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/lungs.png
    - assets/images/profile.jpg


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
